#!/usr/bin/env python3
"""Embed the OTA signing public key into firmware as a C uint8_t array.

Reads:
    firmware/scripts/secrets/signing-key.pub.pem  (default)
    or the path passed via --pubkey

Writes:
    firmware/src/application/SigningPublicKey.h

The header exposes:
    constexpr uint8_t kOtaSigningPublicKeyDer[N] = { ... };
    constexpr size_t  kOtaSigningPublicKeyDerLen = N;

In DER format — same byte layout esp_https_ota's signature
verifier consumes when configured for app-level verification (F5).
PEM is human-readable but base64-padded; DER is the canonical
binary form, ~150 bytes shorter, and what mbedTLS / esp-cryptoauthlib
parse natively.

This script has no third-party dependencies — uses only stdlib +
`openssl` from the shell to convert PEM→DER. Run it once after
generate-signing-key.sh; rerun any time the public key rotates
(which forces a re-flash of every device).
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_PUBKEY = REPO_ROOT / "firmware/scripts/secrets/signing-key.pub.pem"
OUTPUT_HEADER = REPO_ROOT / "firmware/src/application/SigningPublicKey.h"


def pem_to_der(pem_path: Path) -> bytes:
    """Run `openssl rsa -pubin -outform DER` and return the bytes.

    We shell out rather than use cryptography / pyca because the
    firmware project doesn't otherwise depend on a Python crypto
    library — keeping the only dep `openssl`, which the dev box
    already has for generate-signing-key.sh.
    """
    if not shutil.which("openssl"):
        sys.exit(
            "ERROR: openssl not on PATH. Install it (Ubuntu: apt-get install "
            "openssl; macOS: brew install openssl) and rerun."
        )
    result = subprocess.run(
        ["openssl", "rsa", "-pubin", "-in", str(pem_path), "-outform", "DER"],
        check=True,
        capture_output=True,
    )
    return result.stdout


def render_header(der: bytes) -> str:
    body_lines: list[str] = []
    # 12 bytes per line keeps the literal under ~80 columns even
    # with the trailing comma + 4-space indent.
    chunk = 12
    for i in range(0, len(der), chunk):
        line = ", ".join(f"0x{b:02x}" for b in der[i : i + chunk])
        body_lines.append(f"    {line},")
    body = "\n".join(body_lines)

    return f"""#pragma once

// AUTO-GENERATED by firmware/scripts/embed-pubkey.py — do not edit.
// Regenerate by running the script after rotating the OTA signing
// keypair. Source: firmware/scripts/secrets/signing-key.pub.pem.
//
// RSA-3072 public key, DER-encoded SubjectPublicKeyInfo. The OTA
// download path (F4 / F5) verifies firmware signatures against
// this byte array; rotating the keypair requires re-flashing
// every device with the new build.

#include <cstddef>
#include <cstdint>

namespace howler::application {{

constexpr size_t kOtaSigningPublicKeyDerLen = {len(der)};

constexpr uint8_t kOtaSigningPublicKeyDer[kOtaSigningPublicKeyDerLen] = {{
{body}
}};

}}  // namespace howler::application
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument(
        "--pubkey",
        default=str(DEFAULT_PUBKEY),
        help=f"Path to the public key PEM (default: {DEFAULT_PUBKEY})",
    )
    parser.add_argument(
        "--out",
        default=str(OUTPUT_HEADER),
        help=f"Output header path (default: {OUTPUT_HEADER})",
    )
    args = parser.parse_args()

    pem = Path(args.pubkey)
    if not pem.is_file():
        sys.exit(
            f"ERROR: public key not found at {pem}.\n"
            f"       Run firmware/scripts/generate-signing-key.sh first."
        )

    der = pem_to_der(pem)
    header_text = render_header(der)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header_text, encoding="utf-8")

    print(f"Wrote {out} ({len(der)} bytes of DER, {len(header_text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
