-- Auto-generated by backend/scripts/seed-icons.mjs.
-- Source: webapp/src/components/Icon.tsx
-- Format: 24x24 1-bit packed bitmap (72 bytes / icon)
--   row-major, MSB = leftmost pixel, 1 = ink, 0 = bg

-- Insert / refresh seeded icons. Re-running this
-- migration after the script regenerates is safe — the
-- ON CONFLICT clause replaces the bitmap + hash + timestamp.

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('paw', 1, 24, 24, X'000000000000000000000000003700007F8000CD8003FFF006F7F006C0F00380F0003C00007F0000C30001818001818001818001818000FF00000000000000000000000000000000', 'a6e6b7b6a7068f8ba9e8adcd1a90f4b60cb0efef', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('dog', 1, 24, 24, X'0000000000000000000000000000001C3C381FFFF80FC3F00DC3B00FC3F00300C00300C00366C00366C00300C00300C00300C00300C001FF8000FF00000000000000000000000000', '1247f38ab450cd7d711f7e618bda726af0c61d86', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('cat', 1, 24, 24, X'000000000000000000000000007E0001FF800781E00E00700C00300C00300E00700E00700E66700C66300C00300C00300C00300C003007FFE003FFC0000000000000000000000000', 'e8c9cf6e07eb47001ca5d290d15dc036bf54db25', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('broom', 1, 24, 24, X'000000000000000000000600000E00001D800039C00070E000F07001F03803E01803C60000CE0001B80001F00003C0000700000600000C0000180000180000000000000000000000', '82d2189a2d47863e686f36916bf822cd510a2db3', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('home', 1, 24, 24, X'000000000000000000001800003C00007E0000E3000181800300E00E00701E00781E007806006006006006006006006006006006006007FFE007FFE0000000000000000000000000', '4fd597c5a09a5365ca3b652ee4590c448e40789d', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('bowl', 1, 24, 24, X'000000000000000000000000000000000000003C00007E0000C30000C3000000001FFFF81FFFF80800100C00300C003004002006006006006003FFC001FF80000000000000000000', 'c36a6d9ca173bbcdfc34ae111d0b6a8254b5fc89', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('heart', 1, 24, 24, X'00000000000000000000000001E78003FFC00618600C00300C00300C00300C00300400200600600600600300C001818000C300006600003C00001800000000000000000000000000', '299d67e53adcf1b6d67c261874d9d218c34eb040', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('sparkle', 1, 24, 24, X'0000000000000000000018000018000018000018000018000018000018000018001FE7F81FE7F8001800001800001800001800001800001800001800001800000000000000000000', 'da16c1a83e655494dc74291e110dfecda4e49701', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('star', 1, 24, 24, X'000000000000000000001800001800003C00003C0000660001E7801FC3F80C00300E00700700E00381C0018180018180011880037EC003E7C00381C0000000000000000000000000', 'd2a93f4e9dc5908ba005601ce19981c35b354d6d', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('plant', 1, 24, 24, X'0000000000000000000000000000000000000000000381C003E7C0037EC001BD8001DB8000FF00003C0000180000180000180000180000180001FF8001FF80000000000000000000', 'f17f7e5babdc882373cfd3d904b55345dc9b660f', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('flame', 1, 24, 24, X'00000000000000000000000000000000000000C60000E70000F78000DD80019CC00198C00300600200600600600600600600600200400300C001818000FF00003C00000000000000', '9cd5f95afb930ea80330148ba66eb23aca1e6c32', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('bell', 1, 24, 24, X'000000000000000000000000003C0000FF0001C3800300C00300C00600600600600600600600600600600600600600600600600FFFF00FFFF0006600006600003C00001800000000', '1cc8c27c3339c77e84a96b7da38e36f76e521a83', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('briefcase', 1, 24, 24, X'000000000000000000000000007E0000C3000FFFF01FFFF81000081000081000081FFFF81FFFF81000081000081000081000081000081FFFF80FFFF0000000000000000000000000', '33053708b03057ac86d91e8a27990365886126ed', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('book', 1, 24, 24, X'0000000000000000000000000FFFF00FFFF00C3C300C3C300C3C300C3C300C3C300C3C300C3C300C3C300C3C300C3C300C3C300FFFF00FFFF0003C00003C00000000000000000000', '8140b250a842335265311638ce946ea678985466', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('run', 1, 24, 24, X'000000000000000000000780000780000780000780000000000600000600018C0003EC000E78000C1800001800001C00003F0000330000618000618000C0C000C0C0000000000000', 'e414403face38bec18006adf1ec28b8e64948f93', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('pill', 1, 24, 24, X'0000000000000000000000000000000000C00003F0000FB0003F9800771801CE18079C700E39E018738018EE0019FC000DF0000FC000030000000000000000000000000000000000', '124860c188f3e6459cda22a393ada3799b9d299e', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('tooth', 1, 24, 24, X'00000000000000000003C3C007E7E00C3C301800181800181800181800181800180C00300C0030061860063C600224400366C003C3C001C380000000000000000000000000000000', 'c1a7106fd53b27da5efc49f6d4a3420a115ce415', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('clock', 1, 24, 24, X'000000000000000000003C0001FF800381C00600600C18300C1830081810181818181818181C181807180803100C00300C00300600600381C001FF80003C00000000000000000000', '7d9fbe2710e7aae3113d93368d3c14fb452b6a9d', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('calendar', 1, 24, 24, X'00000000000000000000C30000C3000FFFF018C31818C3181800181FFFF81FFFF81800181800181800181800181800181800181800181800180FFFF0000000000000000000000000', '99457624e39943aafc8466940cf6a648d9af823f', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;

INSERT INTO icons (name, format_version, width, height, bitmap, content_hash, updated_at)
VALUES ('check', 1, 24, 24, X'0000000000000000000000000000000000000000000000300000600000C00001800003000C0600060C0003180001B00000E000004000000000000000000000000000000000000000', '8e4b363868f4fd41d91b3ef02b8a60358fd4f229', 1778232998)
ON CONFLICT(name) DO UPDATE SET
  format_version = excluded.format_version,
  width          = excluded.width,
  height         = excluded.height,
  bitmap         = excluded.bitmap,
  content_hash   = excluded.content_hash,
  updated_at     = excluded.updated_at;
